name = "plantilla-website"
compatibility_date = "2024-09-23"

# Pages Functions configuration
[build]
command = ""
cwd = ""
watch_dir = ""

# Environment variables for local development
[vars]
FROM_EMAIL = "noreply@ejemplo.com"
TO_EMAIL = "contacto@ejemplo.com"

# For production, these would be set in Cloudflare Pages dashboard:
# RESEND_API_KEY = "re_xxxxxxxxxx"
# MAILGUN_API_KEY = "your-mailgun-api-key"
# MAILGUN_DOMAIN = "your-domain.mailgun.org"
# SENDGRID_API_KEY = "SG.xxxxxxxxxx"
# EMAILJS_PUBLIC_KEY = "your-emailjs-public-key"
# EMAILJS_SERVICE_ID = "your-service-id"
# EMAILJS_TEMPLATE_ID = "your-template-id"